# Generated by Django 4.2.19 on 2025-02-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('initials', models.CharField(blank=True, max_length=3, null=True)),
                ('score', models.IntegerField()),
                ('game_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
