# Generated by Django 4.2.19 on 2025-02-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown', '0003_numbersgameresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbersgameresult',
            name='high_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
